
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    env_file:
      - .env
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_custom.cnf:/etc/mysql/conf.d/mysql_custom.cnf
    ports:
      - ${MYSQL_PORT}:3306
    command: >
      --max_connections=500
      --innodb_buffer_pool_size=7G
      --innodb_log_file_size=512M
      --innodb_flush_log_at_trx_commit=2
      --innodb_buffer_pool_instances=4
      --max_allowed_packet=64M

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  mysql_data:
